# Generated by Django 2.0.7 on 2018-09-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hikarian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketinfo',
            name='issuingstation',
        ),
        migrations.AlterField(
            model_name='ticketpreplot',
            name='preplot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hikarian.preplot'),
        ),
        migrations.AlterField(
            model_name='ticketpreplot',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hikarian.ticketInfo'),
        ),
    ]
