# Generated by Django 2.0.7 on 2018-09-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hikarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininfo',
            name='startstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='Hikarian.stationInfo'),
        ),
    ]
